import {
  AppState,
  LeagueConfig,
  Player,
  PlayerGroup,
  Team,
  TeamGenerationStats,
  TeamIteration,
  TeamIterationType,
} from '@/types';
import { generateBalancedTeams } from '@/utils/teamGenerator';
import { applyTeamBranding, ensureUniqueTeamNames } from '@/utils/teamBranding';
import { normalizeLeagueConfig } from '@/utils/teamCount';
import { generateFullAiTeams } from '@/services/aiService';

function clonePlayer(player: Player): Player {
  return {
    ...player,
    profile: player.profile ? { ...player.profile } : undefined,
    teammateRequests: [...(player.teammateRequests ?? [])],
    avoidRequests: [...(player.avoidRequests ?? [])],
    teammateRequestsParsed: player.teammateRequestsParsed?.map(request => ({ ...request })),
    unfulfilledRequests: player.unfulfilledRequests?.map(request => ({ ...request })),
  };
}

function cloneTeam(team: Team): Team {
  return {
    ...team,
    players: (team.players ?? []).map(clonePlayer),
    genderBreakdown: {
      M: team.genderBreakdown?.M ?? 0,
      F: team.genderBreakdown?.F ?? 0,
      Other: team.genderBreakdown?.Other ?? 0,
    },
  };
}

function cloneStats(stats?: TeamGenerationStats): TeamGenerationStats | undefined {
  return stats ? { ...stats } : undefined;
}

function clonePlayerGroups(players: Player[], playerGroups: PlayerGroup[]): PlayerGroup[] {
  const playerMap = new Map(players.map(player => [player.id, player]));

  return playerGroups.map(group => ({
    ...group,
    playerIds: [...group.playerIds],
    players: group.playerIds
      .map(playerId => playerMap.get(playerId))
      .filter((player): player is Player => Boolean(player)),
  }));
}

function createIterationId(type: TeamIterationType): string {
  return `${type}-iteration-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

function normalizeNameKey(name: string): string {
  return name.trim().toLocaleLowerCase();
}

function getUniqueCopiedIterationName(sourceName: string, existingNames: string[]): string {
  const usedNames = new Set(existingNames.map(normalizeNameKey));
  const trimmedSourceName = sourceName.trim() || 'Untitled Tab';
  const baseName = trimmedSourceName.replace(/(?:\s+copy(?:\s+\d+)*)+$/i, '').trim() || trimmedSourceName;
  let candidate = `${baseName} Copy`;
  let copyNumber = 2;

  while (usedNames.has(normalizeNameKey(candidate))) {
    candidate = `${baseName} Copy ${copyNumber}`;
    copyNumber += 1;
  }

  return candidate;
}

function cloneResult(
  teams: Team[],
  unassignedPlayers: Player[],
  stats?: TeamGenerationStats
): Pick<TeamIteration, 'teams' | 'unassignedPlayers' | 'stats'> {
  return {
    teams: teams.map(cloneTeam),
    unassignedPlayers: unassignedPlayers.map(clonePlayer),
    stats: cloneStats(stats),
  };
}

function shufflePlayers<T>(items: T[]): T[] {
  const shuffled = [...items];
  for (let index = shuffled.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1));
    [shuffled[index], shuffled[swapIndex]] = [shuffled[swapIndex]!, shuffled[index]!];
  }
  return shuffled;
}

function isLikelyManualIteration(
  teams: Team[] | undefined,
  unassignedPlayers: Player[] | undefined,
  players: Player[] | undefined
): boolean {
  const safeTeams = teams ?? [];

  if (safeTeams.length === 0) {
    return false;
  }

  return safeTeams.every(team => (team.players?.length ?? 0) === 0)
    && (unassignedPlayers?.length ?? 0) >= (players?.length ?? 0);
}

export function createPendingTeamIteration(
  name: string,
  type: Extract<TeamIterationType, 'ai'>
): TeamIteration {
  return {
    id: createIterationId(type),
    name,
    type,
    status: 'generating',
    teams: [],
    unassignedPlayers: [],
    createdAt: new Date().toISOString(),
  };
}

export function createManualTeamIteration(
  players: Player[],
  config: LeagueConfig,
  playerGroups: PlayerGroup[],
  name: string
): TeamIteration {
  const clonedPlayers = players.map(clonePlayer);
  const clonedGroups = clonePlayerGroups(clonedPlayers, playerGroups);
  const result = generateBalancedTeams(clonedPlayers, config, clonedGroups, false, true);

  return {
    id: createIterationId('manual'),
    name,
    type: 'manual',
    status: 'ready',
    generationSource: 'manual',
    ...cloneResult(result.teams, result.unassignedPlayers, result.stats),
    createdAt: new Date().toISOString(),
  };
}

export function createAutoGeneratedAiTeamIteration(
  players: Player[],
  config: LeagueConfig,
  playerGroups: PlayerGroup[],
  name: string,
  variant: 'primary' | 'alternate' = 'primary'
): TeamIteration {
  const clonedPlayers = players.map(clonePlayer);
  const sourcePlayers = variant === 'alternate' ? shufflePlayers(clonedPlayers) : clonedPlayers;
  const clonedGroups = clonePlayerGroups(sourcePlayers, playerGroups);
  const result = generateBalancedTeams(
    sourcePlayers,
    config,
    clonedGroups,
    variant === 'alternate',
    false
  );

  return {
    id: createIterationId('ai'),
    name,
    type: 'ai',
    status: 'ready',
    generationSource: 'fallback',
    ...cloneResult(result.teams, result.unassignedPlayers, result.stats),
    createdAt: new Date().toISOString(),
  };
}

export async function createAiTeamIteration(
  players: Player[],
  config: LeagueConfig,
  playerGroups: PlayerGroup[],
  name: string,
  variant: 'primary' | 'alternate' = 'primary'
): Promise<TeamIteration> {
  const clonedPlayers = players.map(clonePlayer);
  const clonedGroups = clonePlayerGroups(clonedPlayers, playerGroups);
  const result = await generateFullAiTeams(clonedPlayers, config, clonedGroups, variant);

  return {
    id: createIterationId('ai'),
    name,
    type: 'ai',
    status: 'ready',
    generationSource: result.source,
    aiModel: result.aiModel,
    aiResponseId: result.aiResponseId,
    aiResponseIds: result.aiResponseIds,
    ...cloneResult(result.teams, result.unassignedPlayers, result.stats),
    createdAt: new Date().toISOString(),
    errorMessage: result.source === 'fallback'
      ? result.summary || 'AI was unavailable, so the standard builder was used.'
      : result.summary,
  };
}

export function cloneTeamIteration(iteration: TeamIteration): TeamIteration {
  return {
    ...iteration,
    teams: (iteration.teams ?? []).map(cloneTeam),
    unassignedPlayers: (iteration.unassignedPlayers ?? []).map(clonePlayer),
    stats: cloneStats(iteration.stats),
  };
}

export function createCopiedTeamIteration(
  iteration: TeamIteration,
  existingIterations: TeamIteration[]
): TeamIteration {
  const clonedIteration = cloneTeamIteration(iteration);
  const existingIterationNames = existingIterations.map(existingIteration => existingIteration.name || 'Untitled Tab');
  const existingTeamNames = existingIterations.flatMap(existingIteration =>
    (existingIteration.teams ?? []).map(team => team.name)
  );

  return {
    ...clonedIteration,
    id: createIterationId(iteration.type),
    name: getUniqueCopiedIterationName(iteration.name, existingIterationNames),
    teams: ensureUniqueTeamNames(clonedIteration.teams, existingTeamNames, {
      preferAlternativeBranding: true,
    }),
    createdAt: new Date().toISOString(),
    errorMessage: undefined,
  };
}

function isIncompleteIteration(
  iteration: TeamIteration,
  players: Player[]
): boolean {
  return players.length > 0
    && iteration.status === 'ready'
    && (iteration.teams?.length ?? 0) === 0
    && (iteration.unassignedPlayers?.length ?? 0) === 0;
}

function rebuildIncompleteIteration(
  iteration: TeamIteration,
  players: Player[],
  config: LeagueConfig,
  playerGroups: PlayerGroup[]
): TeamIteration {
  const repairedConfig = normalizeLeagueConfig(config);
  const clonedPlayers = players.map(clonePlayer);
  const clonedGroups = clonePlayerGroups(clonedPlayers, playerGroups);

  if (iteration.type === 'manual') {
    const manualResult = generateBalancedTeams(clonedPlayers, repairedConfig, clonedGroups, false, true);

    return {
      ...iteration,
      teams: manualResult.teams.map(cloneTeam),
      unassignedPlayers: manualResult.unassignedPlayers.map(clonePlayer),
      stats: cloneStats(manualResult.stats),
      generationSource: 'manual',
      errorMessage: 'This tab was repaired from incomplete saved data.',
    };
  }

  const generatedResult = generateBalancedTeams(
    clonedPlayers,
    repairedConfig,
    clonedGroups,
    iteration.type === 'ai',
    false
  );

  return {
    ...iteration,
    teams: generatedResult.teams.map(cloneTeam),
    unassignedPlayers: generatedResult.unassignedPlayers.map(clonePlayer),
    stats: cloneStats(generatedResult.stats),
    generationSource: iteration.type === 'ai' ? 'fallback' : 'generated',
    errorMessage: 'This tab was repaired from incomplete saved data.',
  };
}

export function ensureTeamIterations(
  data: Pick<
    AppState,
    'players' | 'teams' | 'unassignedPlayers' | 'stats' | 'playerGroups' | 'config' | 'teamIterations' | 'activeTeamIterationId'
  >
): { teamIterations: TeamIteration[]; activeTeamIterationId: string | null } {
  const normalizedIterations = (data.teamIterations ?? []).map(iteration => {
    const normalizedIteration: TeamIteration = {
      ...cloneTeamIteration(iteration),
      status: iteration.status ?? 'ready',
      generationSource: iteration.generationSource ?? (iteration.type === 'manual' ? 'manual' : iteration.type === 'generated' ? 'generated' : 'ai'),
      createdAt: iteration.createdAt || new Date().toISOString(),
      teams: iteration.teams || [],
      unassignedPlayers: iteration.unassignedPlayers || [],
    };

    const repairedIteration = isIncompleteIteration(normalizedIteration, data.players ?? [])
      ? rebuildIncompleteIteration(normalizedIteration, data.players ?? [], data.config, data.playerGroups || [])
      : normalizedIteration;

    return {
      ...repairedIteration,
      teams: applyTeamBranding(repairedIteration.teams || [], data.playerGroups || [], data.config),
      unassignedPlayers: repairedIteration.unassignedPlayers || [],
    };
  });

  if (normalizedIterations.length > 0) {
    const activeId = normalizedIterations.some(iteration => iteration.id === data.activeTeamIterationId)
      ? data.activeTeamIterationId ?? normalizedIterations[0]!.id
      : normalizedIterations[0]!.id;

    return {
      teamIterations: normalizedIterations,
      activeTeamIterationId: activeId,
    };
  }

  const hasLegacyTeamState = (data.teams?.length ?? 0) > 0 || (data.unassignedPlayers?.length ?? 0) > 0 || Boolean(data.stats);
  if (!hasLegacyTeamState) {
    return {
      teamIterations: [],
      activeTeamIterationId: null,
    };
  }

  const type: TeamIterationType = isLikelyManualIteration(data.teams, data.unassignedPlayers, data.players)
    ? 'manual'
    : 'generated';

  const legacyIteration: TeamIteration = {
    id: createIterationId(type),
    name: type === 'manual' ? 'Manual 1' : 'Generated 1',
    type,
    status: 'ready',
    generationSource: type === 'manual' ? 'manual' : 'generated',
    teams: applyTeamBranding((data.teams || []).map(cloneTeam), data.playerGroups || [], data.config),
    unassignedPlayers: (data.unassignedPlayers || []).map(clonePlayer),
    stats: cloneStats(data.stats),
    createdAt: new Date().toISOString(),
  };

  return {
    teamIterations: [legacyIteration],
    activeTeamIterationId: legacyIteration.id,
  };
}

export function applyTeamIterationToState(state: AppState, iterationId: string | null): AppState {
  if (!iterationId) {
    return {
      ...state,
      activeTeamIterationId: null,
      teams: [],
      unassignedPlayers: [],
      stats: undefined,
    };
  }

  const activeIteration = state.teamIterations?.find(iteration => iteration.id === iterationId);
  if (!activeIteration) {
    return {
      ...state,
      activeTeamIterationId: null,
      teams: [],
      unassignedPlayers: [],
      stats: undefined,
    };
  }

  return {
    ...state,
    activeTeamIterationId: activeIteration.id,
    teams: (activeIteration.teams ?? []).map(cloneTeam),
    unassignedPlayers: (activeIteration.unassignedPlayers ?? []).map(clonePlayer),
    stats: cloneStats(activeIteration.stats),
  };
}

export function syncActiveTeamIterationToState(state: AppState): AppState {
  if (!state.activeTeamIterationId || !state.teamIterations?.length) {
    return state;
  }

  const updatedIterations = state.teamIterations.map(iteration => (
    iteration.id === state.activeTeamIterationId
      ? {
        ...iteration,
        teams: (state.teams ?? []).map(cloneTeam),
        unassignedPlayers: (state.unassignedPlayers ?? []).map(clonePlayer),
        stats: cloneStats(state.stats),
        errorMessage: undefined,
      }
      : iteration
  ));

  return {
    ...state,
    teamIterations: updatedIterations,
  };
}
