import React, { useState } from 'react';
import { ArrowLeft, Mail, RefreshCw, ShieldCheck } from 'lucide-react';
import { adminImportPlayers, adminImportSchedule, adminLogin, adminRetryEmail, adminRunReplacement, adminSendTestEmail, loadAdminOperations } from './api';
import { parseSubPlayerCsv, parseSubScheduleCsv } from './core';
import type { AdminOperationsResponse } from './apiContracts';

export function SubLotteryAdmin() {
  const [pin, setPin] = useState(''); const [authenticated, setAuthenticated] = useState(false); const [data, setData] = useState<AdminOperationsResponse | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [playersCsv, setPlayersCsv] = useState(''); const [scheduleCsv, setScheduleCsv] = useState(''); const [seasonName, setSeasonName] = useState('Current season');
  const refresh = async () => setData(await loadAdminOperations(data?.state?.seasonId));
  const act = async (action: () => Promise<unknown>) => { setBusy(true); setError(''); try { await action(); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Action failed.'); } finally { setBusy(false); } };
  if (!authenticated) return <main className="min-h-screen bg-zinc-50 p-6"><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { await adminLogin(pin); setAuthenticated(true); setData(await loadAdminOperations()); } catch (x) { setError(x instanceof Error ? x.message : 'Login failed.'); } finally { setBusy(false); } }} className="mx-auto mt-20 max-w-md rounded-3xl border-2 bg-white p-6 shadow-lg"><ShieldCheck className="mb-3 h-10 w-10 text-emerald-600"/><h1 className="text-2xl font-black">Sub Lottery Admin</h1><p className="mb-4 text-sm font-bold text-zinc-500">Secure 30-minute operations session.</p><input autoFocus type="password" value={pin} onChange={e => setPin(e.target.value)} placeholder="Admin PIN" className="mb-3 w-full rounded-xl border-2 p-3"/><button disabled={busy} className="w-full rounded-xl bg-emerald-600 p-3 font-black text-white">Sign in</button>{error && <p className="mt-3 font-bold text-red-600">{error}</p>}<a href="/sub-lottery" className="mt-4 block text-center text-sm font-bold text-zinc-500">Back to lottery</a></form></main>;
  const assignments = data?.assignments ?? []; const emails = data?.emails ?? []; const audit = data?.audit ?? [];
  const playerPreview = (() => { try { return parseSubPlayerCsv(playersCsv).length; } catch { return 0; } })(); const schedulePreview = (() => { try { return parseSubScheduleCsv(scheduleCsv).length; } catch { return 0; } })();
  return <main className="min-h-screen bg-zinc-50 p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-5"><header className="flex items-center justify-between"><div><h1 className="text-3xl font-black">Sub Lottery Admin</h1><p className="font-bold text-zinc-500">Week {data?.state?.weekStartDate ?? '—'} · {data?.state?.seasonName}</p></div><div className="flex gap-2"><a href="/sub-lottery" className="rounded-xl border-2 bg-white p-3"><ArrowLeft/></a><button onClick={() => void act(refresh)} className="rounded-xl border-2 bg-white p-3"><RefreshCw/></button></div></header>{error && <div className="rounded-xl bg-red-50 p-3 font-bold text-red-700">{error}</div>}
  <section className="grid gap-3 sm:grid-cols-4">{[['Requests',data?.state?.requests?.length],['Assignments',assignments.length],['Email failures',emails.filter(x=>x.status==='failed').length],['Draw records',data?.draws?.length]].map(([a,b])=><div key={String(a)} className="rounded-2xl border-2 bg-white p-4"><div className="text-xs font-black uppercase text-zinc-500">{a}</div><div className="text-3xl font-black">{b ?? 0}</div></div>)}</section>
  <section className="rounded-3xl border-2 bg-white p-5"><h2 className="mb-3 text-xl font-black">Replacement vacancies</h2>{assignments.filter(x=>x.status==='declined'||x.status==='expired').length===0?<p className="font-bold text-zinc-500">No replacements needed.</p>:assignments.filter(x=>x.status==='declined'||x.status==='expired').map(x=><div key={x.id} className="mb-2 flex items-center justify-between rounded-xl bg-amber-50 p-3"><span className="font-bold">{x.teamName} · {x.playerId} · {x.status}</span><button disabled={busy} onClick={()=>void act(()=>adminRunReplacement(x.id!))} className="rounded-lg bg-amber-500 px-3 py-2 font-black">Run replacement</button></div>)}</section>
  <section className="rounded-3xl border-2 bg-white p-5"><h2 className="mb-3 flex items-center gap-2 text-xl font-black"><Mail/> Email operations</h2><div className="mb-3 flex flex-wrap gap-2">{['winner','winner-confirmation','captain-confirmation','decline','replacement'].map(t=><button key={t} disabled={busy} onClick={()=>void act(()=>adminSendTestEmail(t))} className="rounded-lg border-2 px-3 py-2 text-sm font-black">Test {t}</button>)}</div>{emails.slice(0,20).map(x=><div key={x.id} className="flex items-center justify-between border-t py-2 text-sm"><span>{x.kind ?? 'winner'} · {x.status} · {x.recipientEmail ?? x.playerEmail}</span>{x.status==='failed'&&<button onClick={()=>void act(()=>adminRetryEmail(x.id))} className="font-black text-sky-700">Retry</button>}</div>)}</section>
  <section className="rounded-3xl border-2 bg-white p-5"><h2 className="text-xl font-black">Import preview</h2><p className="mb-3 text-sm font-bold text-zinc-500">Imports preserve season counts by normalized player email. Missing records become inactive.</p><input value={seasonName} onChange={e=>setSeasonName(e.target.value)} className="mb-2 w-full rounded-xl border-2 p-2"/><div className="grid gap-3 md:grid-cols-2"><label className="font-black">Players CSV ({playerPreview} valid)<textarea value={playersCsv} onChange={e=>setPlayersCsv(e.target.value)} rows={6} className="mt-1 w-full rounded-xl border-2 p-2 font-mono text-xs"/></label><label className="font-black">Schedule CSV ({schedulePreview} valid)<textarea value={scheduleCsv} onChange={e=>setScheduleCsv(e.target.value)} rows={6} className="mt-1 w-full rounded-xl border-2 p-2 font-mono text-xs"/></label></div><button disabled={busy||!playerPreview||!schedulePreview} onClick={()=>void act(async()=>{const state=await adminImportPlayers({seasonId:data.state.seasonId,seasonName,adminPin:pin,csvText:playersCsv});await adminImportSchedule({seasonId:state.seasonId,seasonName,adminPin:pin,csvText:scheduleCsv});})} className="mt-3 rounded-xl bg-emerald-600 px-4 py-3 font-black text-white disabled:opacity-40">Import reviewed files</button></section>
  <section className="rounded-3xl border-2 bg-white p-5"><h2 className="mb-3 text-xl font-black">Historical weeks</h2><div className="flex flex-wrap gap-2">{(data?.weeks??[]).map(week=><span key={week} className="rounded-lg border-2 px-3 py-2 text-sm font-bold">Week of {week} · {(data.historicalRequests??[]).filter(r=>r.weekStartDate===week).length} requests</span>)}</div><h3 className="mb-2 mt-4 font-black">Seasons</h3><div className="flex flex-wrap gap-2">{(data?.seasons??[]).map(s=><button key={s.id} onClick={async()=>{setBusy(true);try{setData(await loadAdminOperations(s.id));}finally{setBusy(false);}}} className="rounded-lg border-2 px-3 py-2 text-sm font-bold">{s.name??s.id}</button>)}</div></section>
  <section className="rounded-3xl border-2 bg-white p-5"><h2 className="mb-3 text-xl font-black">Audit log</h2>{audit.slice(0,50).map(x=><div key={x.id} className="border-t py-2 text-sm"><strong>{x.action}</strong> · {x.actor} · {x.createdAt}</div>)}</section></div></main>;
}
